//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertNotification
    {
        public int NotificationID { get; set; }
        public int AlertID { get; set; }
        public string RecipientEmail { get; set; }
        public string RecipientPhone { get; set; }
        public string NotificationType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ReadinessAlert ReadinessAlert { get; set; }
    }
}
