//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificationType()
        {
            this.ReadinessAlerts = new HashSet<ReadinessAlert>();
            this.DepartmentRequirements = new HashSet<DepartmentRequirement>();
            this.EmployeeCertifications = new HashSet<EmployeeCertification>();
            this.ReplacementSuggestions = new HashSet<ReplacementSuggestion>();
        }
    
        public int CertificationTypeID { get; set; }
        public string CertificationName { get; set; }
        public string CertificationCode { get; set; }
        public string Description { get; set; }
        public int ValidityPeriodMonths { get; set; }
        public string CriticalityLevel { get; set; }
        public bool RequiresRenewal { get; set; }
        public string RegulatoryBody { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadinessAlert> ReadinessAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentRequirement> DepartmentRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCertification> EmployeeCertifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplacementSuggestion> ReplacementSuggestions { get; set; }
    }
}
