//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComplianceCenterEntities : DbContext
    {
        public ComplianceCenterEntities()
            : base("name=ComplianceCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlertNotification> AlertNotifications { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<CertificationType> CertificationTypes { get; set; }
        public virtual DbSet<ComplianceReport> ComplianceReports { get; set; }
        public virtual DbSet<DepartmentRequirement> DepartmentRequirements { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmployeeCertification> EmployeeCertifications { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ReadinessAlert> ReadinessAlerts { get; set; }
        public virtual DbSet<ReadinessHistory> ReadinessHistories { get; set; }
        public virtual DbSet<ReplacementSuggestion> ReplacementSuggestions { get; set; }
        public virtual DbSet<ScheduledTask> ScheduledTasks { get; set; }
        public virtual DbSet<ShiftAssignment> ShiftAssignments { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<ComplianceReportResult> sp_GenerateComplianceReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> departmentID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComplianceReportResult>("sp_GenerateComplianceReport", startDateParameter, endDateParameter, departmentIDParameter);
        }
    
        public virtual ObjectResult<ReadinessHistoryResult> sp_GetEmployeeReadinessHistory(Nullable<int> employeeID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReadinessHistoryResult>("sp_GetEmployeeReadinessHistory", employeeIDParameter);
        }
    
        public virtual ObjectResult<HotspotResult> sp_GetHotspots(Nullable<decimal> thresholdScore, Nullable<System.DateTime> date)
        {
            var thresholdScoreParameter = thresholdScore.HasValue ?
                new ObjectParameter("ThresholdScore", thresholdScore) :
                new ObjectParameter("ThresholdScore", typeof(decimal));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HotspotResult>("sp_GetHotspots", thresholdScoreParameter, dateParameter);
        }
    
        public virtual ObjectResult<FutureGapResult> sp_PredictFutureGaps(Nullable<int> departmentID, Nullable<int> daysAhead)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            var daysAheadParameter = daysAhead.HasValue ?
                new ObjectParameter("DaysAhead", daysAhead) :
                new ObjectParameter("DaysAhead", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FutureGapResult>("sp_PredictFutureGaps", departmentIDParameter, daysAheadParameter);
        }
    
        public virtual ObjectResult<DepartmentGapsResult> sp_CalculateDepartmentGaps(Nullable<int> departmentID, Nullable<System.DateTime> date, Nullable<int> shiftID)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var shiftIDParameter = shiftID.HasValue ?
                new ObjectParameter("ShiftID", shiftID) :
                new ObjectParameter("ShiftID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepartmentGapsResult>("sp_CalculateDepartmentGaps", departmentIDParameter, dateParameter, shiftIDParameter);
        }
    
        public virtual ObjectResult<DepartmentReadinessResult> sp_CalculateDepartmentReadiness(Nullable<int> departmentID, Nullable<System.DateTime> date, Nullable<int> shiftID)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var shiftIDParameter = shiftID.HasValue ?
                new ObjectParameter("ShiftID", shiftID) :
                new ObjectParameter("ShiftID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepartmentReadinessResult>("sp_CalculateDepartmentReadiness", departmentIDParameter, dateParameter, shiftIDParameter);
        }
    
        public virtual ObjectResult<ReplacementSuggestionResult> sp_GetReplacementSuggestions(Nullable<int> departmentID, Nullable<int> requiredCertificationTypeID, Nullable<System.DateTime> date, Nullable<int> shiftID, Nullable<int> maxResults)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            var requiredCertificationTypeIDParameter = requiredCertificationTypeID.HasValue ?
                new ObjectParameter("RequiredCertificationTypeID", requiredCertificationTypeID) :
                new ObjectParameter("RequiredCertificationTypeID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var shiftIDParameter = shiftID.HasValue ?
                new ObjectParameter("ShiftID", shiftID) :
                new ObjectParameter("ShiftID", typeof(int));
    
            var maxResultsParameter = maxResults.HasValue ?
                new ObjectParameter("MaxResults", maxResults) :
                new ObjectParameter("MaxResults", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReplacementSuggestionResult>("sp_GetReplacementSuggestions", departmentIDParameter, requiredCertificationTypeIDParameter, dateParameter, shiftIDParameter, maxResultsParameter);
        }
    }
}
