//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplianceReport
    {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string ReportType { get; set; }
        public int GeneratedByUserID { get; set; }
        public Nullable<System.DateTime> ReportPeriodStart { get; set; }
        public Nullable<System.DateTime> ReportPeriodEnd { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileType { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
