//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class ComplianceReportResult
    {
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<int> PeriodDays { get; set; }
        public Nullable<decimal> AvgReadinessScore { get; set; }
        public Nullable<decimal> MinReadinessScore { get; set; }
        public Nullable<decimal> MaxReadinessScore { get; set; }
        public Nullable<int> TotalAlerts { get; set; }
        public Nullable<int> CriticalAlerts { get; set; }
        public Nullable<int> ExpiredCertifications { get; set; }
    }
}
