//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class DepartmentGapsResult
    {
        public string CertificationName { get; set; }
        public string CriticalityLevel { get; set; }
        public int MinimumRequired { get; set; }
        public Nullable<int> ActualCompliant { get; set; }
        public Nullable<int> Gap { get; set; }
        public Nullable<decimal> CertificationScore { get; set; }
    }
}
