//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class DepartmentReadinessResult
    {
        public Nullable<int> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> CalculationDate { get; set; }
        public Nullable<decimal> ReadinessScore { get; set; }
        public Nullable<int> TotalAssigned { get; set; }
        public Nullable<int> TotalPresent { get; set; }
        public Nullable<int> CriticalGaps { get; set; }
        public Nullable<int> HighGaps { get; set; }
        public Nullable<int> MediumGaps { get; set; }
        public Nullable<int> LowGaps { get; set; }
        public string Status { get; set; }
    }
}
