//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentRequirement
    {
        public int RequirementID { get; set; }
        public int DepartmentID { get; set; }
        public int CertificationTypeID { get; set; }
        public int MinimumRequired { get; set; }
        public int Priority { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CertificationType CertificationType { get; set; }
        public virtual Department Department { get; set; }
    }
}
