//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCertification
    {
        public int EmployeeCertificationID { get; set; }
        public int EmployeeID { get; set; }
        public int CertificationTypeID { get; set; }
        public string CertificateNumber { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Status { get; set; }
        public string CertificateFileName { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CertificationType CertificationType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
