//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class FutureGapResult
    {
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string CertificationName { get; set; }
        public string CriticalityLevel { get; set; }
        public Nullable<int> Required { get; set; }
        public Nullable<int> CurrentCompliant { get; set; }
        public Nullable<int> ExpiringCount { get; set; }
        public Nullable<int> ProjectedCompliant { get; set; }
        public Nullable<int> ProjectedGap { get; set; }
        public Nullable<int> MinDaysUntil { get; set; }
        public string AffectedEmployees { get; set; }
        public string Urgency { get; set; }
        public string RecommendedAction { get; set; }
        public Nullable<int> EstimatedCost { get; set; }
    }
}
