//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class HotspotResult
    {
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<decimal> CurrentScore { get; set; }
        public Nullable<int> CriticalGaps { get; set; }
        public Nullable<decimal> AvgScore7Days { get; set; }
        public string Trend { get; set; }
        public Nullable<int> ActiveAlerts { get; set; }
        public Nullable<int> CriticalAlerts { get; set; }
        public Nullable<int> CertsExpiringIn30Days { get; set; }
        public Nullable<decimal> RiskScore { get; set; }
        public string RiskLevel { get; set; }
        public string Recommendation { get; set; }
    }
}
