//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadinessAlert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadinessAlert()
        {
            this.AlertNotifications = new HashSet<AlertNotification>();
        }
    
        public int AlertID { get; set; }
        public int DepartmentID { get; set; }
        public string AlertType { get; set; }
        public string Severity { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> RelatedCertificationTypeID { get; set; }
        public Nullable<int> RelatedEmployeeID { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<int> ResolvedByUserID { get; set; }
        public string ResolutionNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertNotification> AlertNotifications { get; set; }
        public virtual CertificationType CertificationType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
