//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadinessHistory
    {
        public int HistoryID { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime CalculationDate { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public decimal ReadinessScore { get; set; }
        public int TotalRequired { get; set; }
        public int TotalPresent { get; set; }
        public int TotalCompliant { get; set; }
        public int CriticalGaps { get; set; }
        public int HighGaps { get; set; }
        public int MediumGaps { get; set; }
        public int LowGaps { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
