//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class ReadinessHistoryResult
    {
        public int EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string DepartmentName { get; set; }
        public string PositionTitle { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<int> YearsOfService { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ActiveCertifications { get; set; }
        public Nullable<int> ExpiredCertifications { get; set; }
        public Nullable<int> ExpiringIn30Days { get; set; }
    }
}
