//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplacementSuggestion
    {
        public int SuggestionID { get; set; }
        public int DepartmentID { get; set; }
        public int RequiredCertificationTypeID { get; set; }
        public int SuggestedEmployeeID { get; set; }
        public decimal ConfidenceScore { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReviewedByUserID { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string ReviewNotes { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CertificationType CertificationType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
