//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    
    public partial class ReplacementSuggestionResult
    {
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string CurrentDepartment { get; set; }
        public string PositionTitle { get; set; }
        public string CertificateNumber { get; set; }
        public int IsAvailable { get; set; }
        public Nullable<int> TotalCertifications { get; set; }
        public Nullable<int> CriticalCertifications { get; set; }
        public Nullable<int> HighCertifications { get; set; }
        public Nullable<int> PreviousExperienceDays { get; set; }
        public Nullable<System.DateTime> LastWorkDate { get; set; }
        public Nullable<int> MonthsWithCertification { get; set; }
        public Nullable<int> DaysUntilExpiry { get; set; }
        public Nullable<decimal> AvailabilityScore { get; set; }
        public Nullable<decimal> SkillsScore { get; set; }
        public Nullable<decimal> ExperienceScore { get; set; }
        public Nullable<decimal> SeniorityScore { get; set; }
        public Nullable<decimal> MatchScore { get; set; }
        public string Recommendation { get; set; }
        public int ColorIndicator { get; set; }
        public System.DateTime CertificationExpiry { get; set; }
    }
}
