//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceCenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTask
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskType { get; set; }
        public string Schedule { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public string LastRunStatus { get; set; }
        public string LastRunMessage { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
